[libdefaults]
        default_realm = CORP.BANK.SIT.KIWIBANK.INTERNAL
        ticket_lifetime = 24h
        renew_lifetime = 7d
        forwardable = true
        rdns = false
        dns_lookup_realm = false
        kdc_timesync = 1

[realms]
        CORP.BANK.SIT.KIWIBANK.INTERNAL = {
                kdc = CORP.BANK.SIT.KIWIBANK.INTERNAL
                default_domain = CORP.BANK.SIT.KIWIBANK.INTERNAL
        }
        CORP.BANK.NZPFS.CO.NZ = {
                default_domain = corp.bank.nzpfs.co.nz
        }

[domain_realm]
        corp.bank.sit.kiwibank.internal = CORP.BANK.SIT.KIWIBANK.INTERNAL
        corp.bank.sit.kiwibank.internal = CORP.BANK.SIT.KIWIBANK.INTERNAL
